version: 1.0.{build}
image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PGHOST: localhost
  PGUSER: postgres
  PGPASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6
services:
  - postgresql
init:
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%
build_script:
- createdb postgres_repository_test_db
- psql.exe -c "create role postgres_repository_tests with login password 'postgres_repository_tests';"
- cd src && dotnet build -c Release && cd ..
test_script:
- cd tests && dotnet add package Appveyor.TestLogger --version 2.0.0 && dotnet restore && dotnet test --test-adapter-path:. --logger:Appveyor
