version: 1.0.{build}
image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PGUSER: "postgres_repository_tests"
  PGPASSWORD: "postgres_repository_tests"
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6
  POSTGRES_ENV_POSTGRES_USER: postgres_repository_tests
  POSTGRES_ENV_POSTGRES_PASSWORD: postgres_repository_tests
  POSTGRES_ENV_POSTGRES_DB: postgres_repository_test_db
  PGPORT: 5432
  PGHOST: "localhost"
services:
  - postgresql
init:
  - SET PATH=%POSTGRES_PATH%\bin;%PATH%
build_script:
- createdb postgres_repository_test_db
- cd src && dotnet build -c Release && cd ..
test_script:
- cd tests && dotnet add package Appveyor.TestLogger --version 2.0.0 && dotnet restore && dotnet test --test-adapter-path:. --logger:Appveyor
