version: 1.0.{build}
image: Ubuntu1804
services:
  - postgresql101
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PGUSER: "postgres_repository_tests"
  PGPASSWORD: "postgres_repository_tests"
  PGPORT: 5432
  PGHOST: "127.0.0.1"
build_script:
- sh: cd src && dotnet build -c Release && cd ..
test_script:
- sh: PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH% && createdb postgres_repository_test_db && cd tests && dotnet add package Appveyor.TestLogger --version 2.0.0 && dotnet restore && dotnet test --test-adapter-path:. --logger:Appveyor
