version: 1.0.{build}
image: Ubuntu1804
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  PGUSER: "postgres_repository_tests"
  PGPASSWORD: "postgres_repository_tests"
  PGPORT: 5432
  PGHOST: "127.0.0.1"
install:
- sh: sudo apt install -y postgresql postgresql-contrib
build_script:
- sh: cd src && dotnet build -c Release && cd ..
test_script:
- sh: cd tests && dotnet add package Appveyor.TestLogger --version 2.0.0 && dotnet restore && dotnet test --test-adapter-path:. --logger:Appveyor
