language: csharp
sudo: false # faster builds
dist: jammy
services:
  - postgresql
notifications:
  email: false
env:
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - psql -c 'create database postgres_repository_test_db;' -U postgres
  - psql -c "create role postgres_repository_tests with login password 'postgres_repository_tests';"
before_install:
  - git lfs pull
install:
  - dotnet restore
mono: none
dotnet: 6.0
script:
  - dotnet restore
  - cd tests/
  - dotnet test
