version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
      - image: postgres
        environment:
          POSTGRES_DB: postgres_repository_test_db
          POSTGRES_USER: postgres_repository_tests
          POSTGRES_PASSWORD: postgres_repository_tests
    steps:
      - checkout
      - run: sudo apt install -y postgresql-client || true
      - run:
          name: Disable .NET Telemetry
          command: echo 'export DOTNET_CLI_TELEMETRY_OPTOUT=1' >> $BASH_ENV && source $BASH_ENV
      - run:
          name: Restore NuGet dependencies
          command: dotnet restore
      - run:
          name: Run xunit tests
          command: cd tests && dotnet test
